# Run "conda activate py39" first on Ishan's server
# The input folder should contain cameras.bin points3D.bin images.bin, which are generated by calling model.write()
# output_path should be empty
colmap image_undistorter --image_path ./workspace/images/ --input_path ./workspace/input/ --output_path ./workspace/mvs/

colmap patch_match_stereo --workspace_path ./workspace/mvs/

colmap stereo_fusion --output_path ./workspace/mvs/dense.ply --workspace_path ./workspace/mvs/